### ISSUE TITLE
[Bug]: docker-compose.yml镜像源有问题无法pull 且dokcer镜像部署后mongodb无法连接 接口访问502 Bad Gateway

### ISSUE THREAD

**Issue by RubyXun** [cloudtogo/pageplug#111]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

> 已按照官方文档进行配置docker镜像加速 但index.docker.io/cloudtogouser/pageplug-ce:v1.9.37这个镜像源仍无法pull
![Image](https://github.com/user-attachments/assets/d55c363e-434d-4b46-91bd-877f9fa730dd)

![Image](https://github.com/user-attachments/assets/7dd2133d-89e0-48c8-ae23-607066e4931a)

> 更换至image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/cloudtogouser/pageplug-ce:v1.9.37
> 可以成功pull 但容器启动报错
> 抱歉，服务端出错了，我们正在拼命修复
**提示502 Bad Gateway**

### Steps To Reproduce

> [官方支持文档的docker-compose.yml](https://docs.pageplug.cn/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/%E9%83%A8%E7%BD%B2%E5%AE%89%E8%A3%85/%E7%A7%81%E6%9C%89%E5%8C%96%E9%83%A8%E7%BD%B2-%E5%90%ABdocker%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B)
```yml
version: "3"

services:
  pageplug6:
    image: index.docker.io/cloudtogouser/pageplug-ce:v1.9.37
    container_name: pageplug6
    ports:
      - "8564:80"
      - "8569:443"
    volumes:
      - ./stacks:/appsmith-stacks
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
  #   # Uncomment the lines below to enable auto-update
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Update check interval in seconds.
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped
```

> 我更改过的docker-compose.yml
```yml
version: "3"

services:
  pageplug6:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/cloudtogouser/pageplug-ce:v1.9.37
    container_name: pageplug6
    ports:
      - "8564:80"
      - "8569:443"
    volumes:
      - ./stacks:/appsmith-stacks
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
  #   # Uncomment the lines below to enable auto-update
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Update check interval in seconds.
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped
```

### Environment

Production

### Severity

High (Blocker to building or releasing)

### Version

1.9.37

**Comment by RubyXun** [comment]
这些镜像加速都已不可用

腾讯云镜像加速器地址：[https://mirror.ccs.tencentyun.com](https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fmirror.ccs.tencentyun.com%2F&objectId=2434428&objectType=1&isNewArticle=undefined)

中国科学技术大学：[https://docker.mirrors.ustc.edu.cn](https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fdocker.mirrors.ustc.edu.cn%2F&objectId=2434428&objectType=1&isNewArticle=undefined)

Docker官方镜像（中国区）镜像加速：[https://registry.docker-cn.com](https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fregistry.docker-cn.com%2F&objectId=2434428&objectType=1&isNewArticle=undefined)

网易云镜像加速器地址：[http://hub-mirror.c.163.com](https://cloud.tencent.com/developer/tools/blog-entry?target=http%3A%2F%2Fhub-mirror.c.163.com%2F&objectId=2434428&objectType=1&isNewArticle=undefined)

南京大学镜像加速器地址：[https://docker.nju.edu.cn](https://cloud.tencent.com/developer/tools/blog-entry?target=https%3A%2F%2Fdocker.nju.edu.cn%2F&objectId=2434428&objectType=1&isNewArticle=undefined)

**Comment by AppsmithCN** [comment]
之前社区的伙伴分享了一个案例，可以看下这个文档处理下：https://www.cnblogs.com/xyz/p/18567902

**Comment by AppsmithCN** [comment]
1、新版的社区版已推送至阿里云镜像仓库，可以看下这个yml文件，修改镜像地址：registry.cn-beijing.aliyuncs.com/cloudtogo-offical/pageplug-ce:v1.9.38-amd

![Image](https://github.com/user-attachments/assets/b60aa404-87f6-47dc-8b6c-d0d6d3d3b44c)

2、官方文档中的yml文件近期会更新下

**Comment by RubyXun** [comment]
> 1、新版的社区版已推送至阿里云镜像仓库，可以看下这个yml文件，修改镜像地址：registry.cn-beijing.aliyuncs.com/cloudtogo-offical/pageplug-ce:v1.9.38-amd
> 
> ![Image](https://github.com/user-attachments/assets/b60aa404-87f6-47dc-8b6c-d0d6d3d3b44c)
> 
> 2、官方文档中的yml文件近期会更新下

但是现在我按照registry.cn-beijing.aliyuncs.com/cloudtogo-offical/pageplug-ce:v1.9.38-amd这个镜像源拉取了镜像随后 使用官方人员静静发给我的compose-yml

容器启动后依旧报错
```yml
version: "3"

services:
  pageplug6:
    image: registry.cn-beijing.aliyuncs.com/cloudtogo-offical/pageplug-ce:v1.9.38-amd
    container_name: pageplug6
    ports:
      - "8564:80"
      - "8569:443"
    volumes:
      - ./stacks:/appsmith-stacks
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
  #   # Uncomment the lines below to enable auto-update
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Update check interval in seconds.
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped
```
> 问题截图
![Image](https://github.com/user-attachments/assets/5874a42b-b85e-4691-9947-de0b05698e35)

![Image](https://github.com/user-attachments/assets/37ef929c-e34c-4fda-a6aa-1c8e6bee4b49)
