### ISSUE TITLE
Docker 本地化部署失败

### ISSUE THREAD

**Issue by SheddingNeurology** [cloudtogo/pageplug#35]
**🙋🏻‍♂️描述下你的问题**
Docker 本地化部署失败， 总是提示： 
``` bash
Initializing Replica Set for local database
/opt/appsmith/entrypoint.sh: line 140:    14 Illegal instruction     (core dumped) mongod --fork --port 27017 --dbpath "$MONGO_DB_PATH" --logpath "$MONGO_LOG_PATH"
```

安装环境：
CentOS 7 
Docker version 20.10.23, build 7155243
Docker Compose version v2.18.1

docker-compose.yml :
``` yml


version: "3"

services:
  pageplug:
    image: index.docker.io/cloudtogouser/pageplug-ce
    container_name: pageplug
    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
  #   # Uncomment the lines below to enable auto-update
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"

  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # Update check interval in seconds.
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped
```

**🧑🏻‍💻贴图**
![image](https://github.com/cloudtogo/pageplug/assets/16640462/1dc6fc89-6d0a-40b8-8a8a-4e8ea7d6d142)

**🥳复现流程**
尝试了更改端口
重新创建了 Ubuntu 22.04 重新拉取 也是同样报错
